[font]
size = 12.0

[font.normal]
# family = "Inconsolata Nerd Font Mono"
family = "SF Mono Terminal"
style = "Regular"

[colors.primary]
background = "#191D27"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Shift|Control"

# [window]
# opacity = 0.9
