[font]
size = 10.0

# [font.normal]
# family = "SF Mono Terminal"
# style = "Regular"

[colors.primary]
background = "#191D27"

[window]
opacity = 0.9

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Shift|Control"
